### ISSUE TITLE
Create a `GUIDE` application

### ISSUE THREAD

**Issue by hildogjr** [cjnaz/RCloneSync#13]
I know that is reproduce some already existent (at least to some could servers). But create a menu with process bars inside inside an icon close to clock in KDE or GONOME taskbar will make this application more attractive for new users.
Maybe this is possible be using the wxPython library.

**Comment by cjnaz** [comment]
This would make sense for on-demand executions, and probably not when running as a cron job, which is how I run it.  I don't currently have the skills for creating a GUI interface for this tool.  I welcome such contributions, or feel free to fork the project.  
regards,
cjn
