### ISSUE TITLE
Standartize the the argument options

### ISSUE THREAD

**Issue by hildogjr** [cjnaz/RCloneSync#15]
Standartize the the argument options, for Unix they are usually lowercase and the main command have a one letter alias. So:
--help, -h
--first, -f  % For first sync.
--checkaccess
--force, -f
--excludelistfile, -e
--verbose, -v
--rcverbose
--dryrun

Also add a `__VERSION__` variable for control propose, that returns the version of the script with the argument:
--version, -V % V for versions is normally uppercase.

**Comment by cjnaz** [comment]
Most changes covered in [rclonesync V2](https://github.com/cjnaz/rclonesync-V2).
