### ISSUE TITLE
Add `--cron` %t argument

### ISSUE THREAD

**Issue by hildogjr** [cjnaz/RCloneSync#16]
Adding a `--cron %time%` argument could be interesting to th user (not familiar with Linux), so running `--FirstSync --cron %time%` leave the system full configured.
In the script to create the the crontab line use

    if sys.version > (3,0)
       ## Cron using `python3 RCloneSync.py ....`
    else
       ## Cron using python2 `python RCloneSync.py ...`

**Comment by cjnaz** [comment]
I'm going to pass on this one.  Setting up a cron job is somewhat user specific, depends where RCloneSync is placed (or in the path), etc.  I'll leave it to the user to learn more about their environment.

Here's my (filtered) crontab entry, for example:

`          15,45    *       *              *                  *    /<path to script>/RCloneSync.py GDrive:  /<path to Local>/GoogleDrive --CheckAccess >> <path to logdir>/GDrive_runlog 2>&1`
