### ISSUE TITLE
Script won't run

### ISSUE THREAD

**Issue by trinaryouroboros** [cjnaz/RCloneSync#21]
I get the following error when running the script:

```
$ ./RCloneSync.py gdrive: /gdrive/ --CheckAccess --Verbose
2018-06-12 17:39:44,137/:  ***** BiDirectional Sync for Cloud Services using RClone *****
Traceback (most recent call last):
  File "./RCloneSync.py", line 472, in <module>
    logging.error ("ERROR  rclone not installed?\nError message: {}\n".format(sys.exc_info()[1])); exit()
ValueError: zero length field name in format
```

I look up that line, seems like it just gets a list of the remotes:

```
    try:
        clouds = subprocess.check_output(['rclone', 'listremotes'])
    except subprocess.CalledProcessError, e:
        logging.error ("ERROR  Can't get list of known remotes.  Have you run rclone config?"); exit()
    except:
        logging.error ("ERROR  rclone not installed?\nError message: {}\n".format(sys.exc_info()[1])); exit()
    clouds = clouds.split()
```

To verify that the command runs, I test it out:

```
$ rclone listremotes
gdrive:
```

Not sure what's going on here.

I'm using CentOS 6, Python 2.6.6

**Comment by cjnaz** [comment]
I recall Python 2.6 requires the string substitutions `{}` to be numbered.  You might want to work on porting the tool to 2.6, or I suggest that you install Python 2.7.x as a second Python install.  Google for such instructions.  You want to leave the original 2.6 install in place and unchanged since other applications rely on it.

**Comment by trinaryouroboros** [comment]
Yeah, I was kind of hoping to avoid that on this particular system. Oh well.

**Comment by cjnaz** [comment]
You're welcome to fork the code and port it to Py 2.6.  Have fun.  :>
