### ISSUE TITLE
Handling Google Documents

### ISSUE THREAD

**Issue by cjnaz** [cjnaz/RCloneSync#22]
Goggle document files are created via the web interface to Google Drive, and appear without any file 
extension on the web interface.  They are not stored as standard files, and thus cannot be natively 
copied off of and back onto the Google Drive directory tree.  A native Google document file can only 
exist on the Google Drive.  Instead, they may be exported in various formats that are supported by 
third party tools, such as Microsoft Excel (.xlsx), or OpenDocument format (.odt).  Within the 
web-based Google document tool (such as Google Sheets) the document may be saved to a normal file 
in various formats via File > Download as > …, which creates a real file in the browser's download 
directory.  

An rclone lsl of the Google Drive for a native Google document will show up as having an extension 
appropriate for the document type, such as .xlsx, .docx, etc (based on the --drive-formats switch), 
while the Google Drive web interface shows no file extension.  Also, the Google document will show 
no size on the web interface, while rclone lsl returns a size of -1.  An rclone copy of a Google 
document will effectively export the document to a normal file, again based on the --drive-formats 
switch.  The exported file will have a real size and have the exact same date-stamp as the original 
Google document file.  

The problem comes up if we attempt to upload a modified exported document, with the same name, 
back to Google Drive:  "Failed to copy: can't update a google document".  Similarly, deleting the 
local copy and then rclone syncing local to Drive: results in "Couldn't delete: can't delete a google 
document".

**Proposed behavior for rclonesync:**
- A new --export-google-docs switch will export (copy to Local) every found Google document as 
<docname>_export.<ext>.  The final rclone sync will put a copy of the exported document on Google 
Drive as well.  The date-stamp on the file will match the original Google document.

- Later, with --export-google-docs, If the native Google document datestamp is newer, and the 
existing exported file is unchanged (relative to the prior rclonesync), then the document will 
be exported again, replacing the current _export file.

- If the exported file is changed (newer) then it will be synchronized as usual/normal, but the 
native Google document cannot be updated.  Effectively, the file version and the native version 
are out of sync.

- If the exported file had previously been changed, and now the native Google document is changed, 
then --export-google-docs will blast/replace the file version.  User beware.  There is no reliable 
way to detect that the file version and the native Google document version have both been 
modified.  The user is advised to rename the modified file version if he/she plans to subsequently 
edit the native Google document via the web interface.

- If --export-google-docs switch is not set then all Google document files (as indicated by 
file size -1) will be ignored.  Previously exported documents (which are now regular files) 
will be synchronized as usual.

**DOES THIS LOOK LIKE THE BEST / PROPER HANDLING?  COMMENTS PLEASE.**

**Comment by Fabian42** [comment]
The official Google Drive client for Windows just creates a link to the Google Document with the correct icon (doc, sheet, etc.). I would prefer this, because I use Google Docs for document creation and editing (I don't even have a program installed for that). For offline copies of Google documents, the Chrome extension by Google can be used that makes Google Docs work offline almost as if you had a connection. It's officially supported and already handles edit conflicts.

Remark about the importance of this issue: Currently RCloneSync does not work for me at all because of this, because --firstSync fails. I don't know how it behaves for others, it should be the same for everyone who has a Google document on his account.

**Comment by cjnaz** [comment]
Please direct discussion to the [V2 repo issue #1](https://github.com/cjnaz/rclonesync-V2/issues/1).
